### ISSUE TITLE
Add a function called `load_pred_model`; Refactor `assets`

### ISSUE THREAD

**Issue by BirkhoffG** [BirkhoffG/ReLax#152]
## TODO

- [x]  Implement a new function called `load_pred_model`. This function should be implemented in the `03_training_module.ipynb`. The API should look like:

```python
def load_pred_model(data_name: str) -> Tuple[hk.Params, PredictiveTrainingModule]:
    ...
```

You can simply call this function to load existing checkpoints:
```python
# This load trained parameters and predictive training module of the adult dataset
params, module = load_pred_model('adult') 
```
- [x]  Train the predictive models and save params of ALL available datasets
    * We automatically save the best model's weight when calling `train_model` and specify the `monitor_metrics` in the `t_configs`. You should find the parameters under the `checkpoint` folder under `log/version_**` folder.

- [x] Refactor the asset folder. We should categorize those assets based on the data name. 
    - Each sub directory should contain (1) csv data; (2) data configs; (3) pred model params. It should look like this:
```
- assets
    - adult
        - data.csv # This is the `s_adult.csv`
        - configs.json # This is the `adult.json`
        - pred_model
            - tree.pkl
            - params.npy
```
- [x] Finally, change the URL link for downloading dataset in `load_data`

## Notes

1. You should use `save_checkpoint` and `load_checkpoint` in `relax._ckpt_manager.py` to save and load the pretrained model's parameters.
