### ISSUE TITLE
v0.2 Roadmap

### ISSUE THREAD

**Issue by BirkhoffG** [BirkhoffG/ReLax#190]
- [ ] Show benchmark results in the docsite or wandb
- [ ] Decouple API in recourse methods 
- [ ] Decouple API in `module.py` and `trainer.py`
- [ ] Support multi-class setting

**Comment by BirkhoffG** [comment]
## High-level One-Liner APIs

* `relax.generate_cf_explanations`
* `relax.evaluate_cfs`

```python
relax.generate_cf_explanations(
    cf_module: BaseCFModule, # Recourse Explanation Module. 
    datamodule: TabularDataModule, # Data Module.
    pred_fn: callable = None, # Predictive function. If None, start training the model.
    strategy: str | BaseGenerationStrategy = 'vmap', # Parallelism Strategy for generating CFs.
    t_configs: TrainingConfigs = None, # Training configs for `BaseParametricCFModule`.
    pred_fn_args: dict = None # auxiliary arguments for `pred_fn`.
) -> Explanation:
    ...

relax.evaluate_cfs(
    cf_exp: Explanation, # CF Explanations
    metrics: Iterable[Union[str, BaseEvalMetrics]] = None, # A list of Metrics. Can be `str` or a subclass of `BaseEvalMetrics`
    return_dict: bool = True, # return a dictionary or not (default: True)
    return_df: bool = False # return a pandas Dataframe or not (default: False)
):
```

**Comment by BirkhoffG** [comment]
## Mid-level Modules

* `CFModule`
* `DataModule`
* `MLModule`

### Other Modules

* `Strategy`
* `Explanation`
* `Metrics`
